# Generated by Django 2.2.2 on 2019-06-15 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char_start_src', models.IntegerField()),
                ('char_end_src', models.IntegerField()),
                ('char_start_dst', models.IntegerField()),
                ('char_end_dst', models.IntegerField()),
                ('score', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': '09. Alignments',
                'ordering': ('witness_src',),
            },
        ),
        migrations.CreateModel(
            name='AlignmentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
            ],
            options={
                'verbose_name_plural': '10. Alignment Types',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char_start', models.IntegerField()),
                ('char_end', models.IntegerField()),
                ('json_content', models.CharField(default='', max_length=500)),
            ],
            options={
                'verbose_name_plural': '12. Annotations',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='AnnotationCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
            ],
            options={
                'verbose_name_plural': '15. AnnotationCategories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='AnnotationParent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
            ],
            options={
                'verbose_name_plural': '16. Annotation Parents',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='AnnotationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
            ],
            options={
                'verbose_name_plural': '14. AnnotationTypes',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
            ],
            options={
                'verbose_name_plural': '03. Collections',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Digitiser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
            ],
            options={
                'verbose_name_plural': '01. Digitisers',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
            ],
            options={
                'verbose_name_plural': '05. Texts',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Witness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('digitiser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='editor.Digitiser')),
                ('text', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='editor.Text')),
            ],
            options={
                'verbose_name_plural': '06. Witnesses',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
            ],
            options={
                'verbose_name_plural': '04. Works',
                'ordering': ('name',),
            },
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ('name',), 'verbose_name_plural': '02. Languages'},
        ),
        migrations.CreateModel(
            name='WorkInCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('collection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='editor.Collection')),
            ],
            options={
                'verbose_name_plural': '08. Works in Collection',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='WitnessPartition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(default='', max_length=5000)),
                ('char_start', models.IntegerField()),
                ('char_end', models.IntegerField()),
                ('witness', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='editor.Witness')),
            ],
            options={
                'verbose_name_plural': '07. Witness Partitions',
                'ordering': ('witness',),
            },
        ),
        migrations.AddField(
            model_name='text',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='editor.Language'),
        ),
        migrations.AddField(
            model_name='text',
            name='work',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='editor.Work'),
        ),
        migrations.CreateModel(
            name='AnnotationLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char_start', models.IntegerField()),
                ('char_end', models.IntegerField()),
                ('score', models.IntegerField()),
                ('certainty', models.IntegerField()),
                ('annotation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='editor.Annotation')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='editor.AnnotationCategory')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='editor.AnnotationType')),
                ('witness', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='editor.Witness')),
            ],
            options={
                'verbose_name_plural': '13. AnnotationLog',
                'ordering': ('score',),
            },
        ),
        migrations.AddField(
            model_name='annotation',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='editor.AnnotationCategory'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='editor.AnnotationType'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='witness',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='editor.Witness'),
        ),
        migrations.CreateModel(
            name='AlignmentLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char_start_src', models.IntegerField()),
                ('char_end_src', models.IntegerField()),
                ('char_start_dst', models.IntegerField()),
                ('char_end_dst', models.IntegerField()),
                ('score', models.IntegerField()),
                ('alignment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='editor.Alignment')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='editor.AlignmentType')),
                ('witness_dst', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='witness_dst_log', to='editor.Witness')),
                ('witness_src', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='witness_src_log', to='editor.Witness')),
            ],
            options={
                'verbose_name_plural': '11. Alignment Log Entries',
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='alignment',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='editor.AlignmentType'),
        ),
        migrations.AddField(
            model_name='alignment',
            name='witness_dst',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='witness_dst', to='editor.Witness'),
        ),
        migrations.AddField(
            model_name='alignment',
            name='witness_src',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='witness_src', to='editor.Witness'),
        ),
    ]
