# Generated by Django 2.1.3 on 2019-06-16 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0002_auto_20190615_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='workincollection',
            name='number',
            field=models.IntegerField(default='', max_length=200),
        ),
    ]
