# Generated by Django 2.1.3 on 2019-06-16 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0003_workincollection_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workincollection',
            options={'ordering': ('collection', 'number'), 'verbose_name_plural': '08. Works in Collection'},
        ),
    ]
