# Generated by Django 2.2.2 on 2019-06-16 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0006_auto_20190616_1159'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workincollection',
            options={'ordering': ('name', 'collection'), 'verbose_name_plural': '08. Works in Collection'},
        ),
    ]
