# Generated by Django 2.2.2 on 2019-06-16 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0007_auto_20190616_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='workincollection',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
