# Generated by Django 2.2.2 on 2019-06-16 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0009_auto_20190616_1215'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='annotationcategory',
            options={'ordering': ('name',), 'verbose_name_plural': '15. Annotation Categories'},
        ),
        migrations.AlterModelOptions(
            name='annotationlog',
            options={'ordering': ('score',), 'verbose_name_plural': '13. Annotation Log Entries'},
        ),
        migrations.AlterModelOptions(
            name='annotationtype',
            options={'ordering': ('name',), 'verbose_name_plural': '14. Annotation Types'},
        ),
    ]
