# Generated by Django 2.2.2 on 2019-06-16 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0010_auto_20190616_1219'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workincollection',
            options={'ordering': ('name', 'collection', 'number'), 'verbose_name_plural': '08. Works in Collections'},
        ),
    ]
