# Generated by Django 2.2.2 on 2019-06-16 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0012_auto_20190616_1224'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workincollection',
            options={'ordering': ('collection', 'number', 'collection'), 'verbose_name_plural': '08. Works in Collections'},
        ),
    ]
