# Generated by Django 2.2.2 on 2019-06-16 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0014_auto_20190616_1325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workincollection',
            name='name',
        ),
        migrations.AddField(
            model_name='workincollection',
            name='work',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='editor.Work'),
        ),
    ]
