# Generated by Django 2.2.2 on 2019-06-16 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0015_auto_20190616_1330'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workincollection',
            options={'ordering': ('work', 'number', 'collection'), 'verbose_name_plural': '08. Works in Collections'},
        ),
    ]
