# Generated by Django 2.2.2 on 2019-06-16 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0016_auto_20190616_1344'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alignmentlog',
            options={'ordering': ('witness_src',), 'verbose_name_plural': '11. Alignment Log Entries'},
        ),
    ]
