# Generated by Django 2.1.3 on 2019-06-18 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0020_auto_20190616_1459'),
    ]

    operations = [
        migrations.CreateModel(
            name='WitnessFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(default='', max_length=500)),
                ('char_start', models.IntegerField()),
                ('char_end', models.IntegerField()),
                ('witness', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='editor.Witness')),
            ],
            options={
                'verbose_name_plural': '07. Witness Files',
                'ordering': ('witness',),
            },
        ),
        migrations.AlterModelOptions(
            name='alignment',
            options={'ordering': ('witness_src',), 'verbose_name_plural': '10. Alignments'},
        ),
        migrations.AlterModelOptions(
            name='alignmentlog',
            options={'ordering': ('-date', 'witness_src'), 'verbose_name_plural': '12. Alignment Log Entries'},
        ),
        migrations.AlterModelOptions(
            name='alignmenttype',
            options={'ordering': ('name',), 'verbose_name_plural': '11. Alignment Types'},
        ),
        migrations.AlterModelOptions(
            name='annotation',
            options={'ordering': ('witness', 'char_start'), 'verbose_name_plural': '13. Annotations'},
        ),
        migrations.AlterModelOptions(
            name='annotationcategory',
            options={'ordering': ('parent', 'name'), 'verbose_name_plural': '16. Annotation Categories'},
        ),
        migrations.AlterModelOptions(
            name='annotationlog',
            options={'ordering': ('-date', 'score'), 'verbose_name_plural': '14. Annotation Log Entries'},
        ),
        migrations.AlterModelOptions(
            name='annotationtype',
            options={'ordering': ('name',), 'verbose_name_plural': '15. Annotation Types'},
        ),
        migrations.AlterModelOptions(
            name='witnesspartition',
            options={'ordering': ('witness',), 'verbose_name_plural': '08. Witness Partitions'},
        ),
        migrations.AlterModelOptions(
            name='workincollection',
            options={'ordering': ('work', 'number', 'collection'), 'verbose_name_plural': '09. Works in Collections'},
        ),
    ]
