# Generated by Django 2.1.3 on 2019-06-19 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0021_auto_20190618_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='witnessfile',
            name='note',
            field=models.CharField(default='', max_length=500),
        ),
    ]
