# Generated by Django 2.2.2 on 2019-06-20 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0023_auto_20190620_0902'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WitnessFile',
            new_name='WitnessIndex',
        ),
        migrations.AlterModelOptions(
            name='witnessindex',
            options={'ordering': ('witness',), 'verbose_name_plural': '07. Witness Indexes'},
        ),
    ]
