# Generated by Django 2.2.2 on 2019-06-20 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0024_auto_20190620_0949'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workincollection',
            options={'ordering': ('number', 'collection', 'work'), 'verbose_name_plural': '09. Works in Collections'},
        ),
    ]
