# Generated by Django 2.1.3 on 2019-06-21 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0026_auto_20190621_1148'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='witnesspartition',
            options={'ordering': ('witness', '-char_start'), 'verbose_name_plural': '08. Witness Partitions'},
        ),
    ]
