# Generated by Django 2.1.3 on 2019-06-21 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0027_auto_20190621_1152'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='witnesspartition',
            options={'ordering': ('witness', 'char_start'), 'verbose_name_plural': '08. Witness Partitions'},
        ),
    ]
