# Generated by Django 2.1.3 on 2019-06-21 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0028_auto_20190621_1153'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='annotationlog',
            options={'ordering': ('-date',), 'verbose_name_plural': '14. Annotation Log Entries'},
        ),
        migrations.RemoveField(
            model_name='annotationlog',
            name='score',
        ),
    ]
