# Generated by Django 2.1.3 on 2019-09-28 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0029_auto_20190621_1304'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='annotationparent',
            options={'ordering': ('name',), 'verbose_name_plural': '17. Annotation Parents'},
        ),
    ]
