# Generated by Django 2.1.3 on 2019-10-09 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0030_auto_20190928_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alignmentlog',
            name='char_end_dst',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
