# Generated by Django 2.1.3 on 2019-11-04 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0033_dictionary_dictionaryentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotationlog',
            name='certainty',
        ),
    ]
