# Generated by Django 2.1.3 on 2019-11-18 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0034_remove_annotationlog_certainty'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dictionaryentry',
            options={'ordering': ('entry1',), 'verbose_name_plural': '19. Dictionary Entries'},
        ),
        migrations.RenameField(
            model_name='dictionaryentry',
            old_name='name',
            new_name='entry1',
        ),
        migrations.AddField(
            model_name='dictionaryentry',
            name='dictionary',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='editor.Dictionary'),
        ),
        migrations.AddField(
            model_name='dictionaryentry',
            name='entry2',
            field=models.CharField(default='', max_length=200),
        ),
    ]
