# Generated by Django 2.2.2 on 2019-09-28 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default='', max_length=200)),
                ('content', models.TextField(default='', help_text='Enter the section content.', max_length=6000)),
                ('notes', models.CharField(default='notes', max_length=1000)),
            ],
            options={
                'verbose_name_plural': 'Sections',
                'ordering': ('number',),
            },
        ),
    ]
