# Generated by Django 2.2.2 on 2019-09-28 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0030_auto_20190928_1156'),
        ('optools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='witness',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='editor.Witness'),
        ),
    ]
