# Generated by Django 2.2.2 on 2019-09-28 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('optools', '0002_section_witness'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionAlignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bleuvalue', models.CharField(default='', max_length=200)),
                ('section1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sectionalignment_section1', to='optools.Section')),
                ('section2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sectionalignment_section2', to='optools.Section')),
            ],
            options={
                'verbose_name_plural': 'Section Alignments',
                'ordering': ('section1', 'section2'),
            },
        ),
    ]
