# Generated by Django 2.1.3 on 2019-10-04 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optools', '0005_auto_20190928_1413'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('text', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='section',
            name='witness',
        ),
        migrations.RemoveField(
            model_name='sectionalignment',
            name='section1',
        ),
        migrations.RemoveField(
            model_name='sectionalignment',
            name='section2',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
        migrations.DeleteModel(
            name='SectionAlignment',
        ),
    ]
